import { Category, Country, MovieType } from '../types/movie.type';

export const MOVIE_TYPE: MovieType[] = [
  'phim-le',
  'phim-bo',
  'phim-chieu-rap',
  'hoat-hinh',
  'tv-shows',
  'phim-vietsub',
  'phim-thuyet-minh',
  'phim-long-tieng',
];

export const titlePageMapping: Partial<
  Record<MovieType | Country | Category, any>
> = {
  'phim-le': 'Phim lẻ',
  'phim-bo': 'Phim bộ',
  'phim-chieu-rap': 'Phim chiếu rạp',
  'hoat-hinh': 'Phim hoạt hình',
  subteam: 'Phim độc quyền',
  'tv-shows': 'Chương trình truyền hình',
  'phim-vietsub': 'Phim phụ đề',
  'phim-thuyet-minh': 'Phim thuyết minh',
  'phim-long-tieng': 'Phim lồng tiếng',
  'viet-nam': 'Phim Việt Nam',
  'trung-quoc': 'Phim Trung Quốc',
  'thai-lan': 'Phim Thái Lan',
  'hong-kong': 'Phim Hồng Kông',
  phap: 'Phim Pháp',
  duc: 'Phim Đức',
  'ha-lan': 'Phim Hà Lan',
  mexico: 'Phim Mexico',
  'thuy-dien': 'Phim Thụy Điển',
  philippines: 'Phim Philippines',
  'dan-mach': 'Phim Đan Mạch',
  'thuy-si': 'Phim Thụy Sĩ',
  ukraina: 'Phim Ukraina',
  'han-quoc': 'Phim Hàn Quốc',
  'au-my': 'Phim Âu Mỹ',
  'an-do': 'Phim Ấn Độ',
  canada: 'Phim Canada',
  'tay-ban-nha': 'Phim Tây Ban Nha',
  indonesia: 'Phim Indonesia',
  'ba-lan': 'Phim Ba Lan',
  malaysia: 'Phim Malaysia',
  'bo-dao-nha': 'Phim Bồ Đào Nha',
  uae: 'Phim UAE',
  'chau-phi': 'Phim Châu Phi',
  'a-rap-xe-ut': 'Phim Ả Rập Xê Út',
  'nhat-ban': 'Phim Nhật Bản',
  'dai-loan': 'Phim Đài Loan',
  anh: 'Phim Anh',
  'quoc-gia-khac': 'Phim quốc gia khác',
  'tho-nhi-ky': 'Phim Thổ Nhĩ Kỳ',
  nga: 'Phim Nga',
  uc: 'Phim Úc',
  brazil: 'Phim Brazil',
  y: 'Phim Ý',
  'na-uy': 'Phim Na Uy',
  'hanh-dong': 'Phim Hành Động',
  'lich-su': 'Phim Lịch Sử',
  'co-trang': 'Phim Cổ Trang',
  'chien-tranh': 'Phim Chiến Tranh',
  'vien-tuong': 'Phim Viễn Tưởng',
  'kinh-di': 'Phim Kinh Dị',
  'tai-lieu': 'Phim Tài Liệu',
  'bi-an': 'Phim Bí Ẩn',
  'phim-18': 'Phim 18+',
  'tinh-cam': 'Phim Tình Cảm',
  'tam-ly': 'Phim Tâm Lý',
  'the-thao': 'Phim Thể Thao',
  'phieu-luu': 'Phim Phiêu Lưu',
  'am-nhac': 'Phim Âm Nhạc',
  'gia-dinh': 'Phim Gia Đình',
  'hoc-duong': 'Phim Học Đường',
  'hai-huoc': 'Phim Hài Hước',
  'hinh-su': 'Phim Hình Sự',
  'vo-thuat': 'Phim Võ Thuật',
  'khoa-hoc': 'Phim Khoa Học',
  'than-thoai': 'Phim Thần Thoại',
  'chinh-kich': 'Phim Chính Kịch',
  'kinh-dien': 'Phim Kinh Điển',
};

export const CountriesArray: Country[] = [
  'viet-nam',
  'trung-quoc',
  'thai-lan',
  'hong-kong',
  'phap',
  'duc',
  'ha-lan',
  'mexico',
  'thuy-dien',
  'philippines',
  'dan-mach',
  'thuy-si',
  'ukraina',
  'han-quoc',
  'au-my',
  'an-do',
  'canada',
  'tay-ban-nha',
  'indonesia',
  'ba-lan',
  'malaysia',
  'bo-dao-nha',
  'uae',
  'chau-phi',
  'a-rap-xe-ut',
  'nhat-ban',
  'dai-loan',
  'anh',
  'quoc-gia-khac',
  'tho-nhi-ky',
  'nga',
  'uc',
  'brazil',
  'y',
  'na-uy',
] as const;

export const LanguagesArray = ['long-tieng', 'thuyet-minh', 'vietsub'] as const;

export const CategoriesArray: Category[] = [
  'hanh-dong',
  'lich-su',
  'co-trang',
  'chien-tranh',
  'vien-tuong',
  'kinh-di',
  'tai-lieu',
  'bi-an',
  'tinh-cam',
  'phim-18',
  'tam-ly',
  'the-thao',
  'phieu-luu',
  'am-nhac',
  'gia-dinh',
  'hoc-duong',
  'hai-huoc',
  'hinh-su',
  'vo-thuat',
  'khoa-hoc',
  'than-thoai',
  'chinh-kich',
  'kinh-dien',
] as const;

// Object.fromEntries() giúp chuyển đổi một mảng các cặp [key, value] thành một đối tượng.
// Vd: Object.fromEntries([['key1', 'value1'], ['key2', 'value2']]) => { key1: 'value1', key2: 'value2' }
// Partial<Record<...>> giúp định nghĩa kiểu cho đối tượng kết quả.
// Object.entries(titlePageMapping) lấy tất cả các cặp [key, value] từ đối tượng titlePageMapping.
// Vd: Object.entries({ a: 1, b: 2 }) => [['a', 1], ['b', 2]]

export const generateMetaData: Partial<
  Record<MovieType | Country | Category, any>
> = Object.fromEntries(
  Object.entries(titlePageMapping).map(([key, title]) => [
    key,
    {
      title: `${title} - Xem phim online miễn phí`,
      description: `Xem ngay ${title} chất lượng cao, cập nhật nhanh nhất tại PHOFLIX-V3.`,
    },
  ]),
);
