export type Category =
  | 'hanh-dong'
  | 'lich-su'
  | 'co-trang'
  | 'chien-tranh'
  | 'vien-tuong'
  | 'kinh-di'
  | 'tai-lieu'
  | 'bi-an'
  | 'phim-18'
  | 'tinh-cam'
  | 'tam-ly'
  | 'the-thao'
  | 'phieu-luu'
  | 'am-nhac'
  | 'gia-dinh'
  | 'hoc-duong'
  | 'hai-huoc'
  | 'hinh-su'
  | 'vo-thuat'
  | 'khoa-hoc'
  | 'than-thoai'
  | 'chinh-kich'
  | 'kinh-dien'
  | 'mien-tay'
  | 'tre-em';

export type Country =
  | 'viet-nam'
  | 'trung-quoc'
  | 'thai-lan'
  | 'hong-kong'
  | 'phap'
  | 'duc'
  | 'ha-lan'
  | 'mexico'
  | 'thuy-dien'
  | 'philippines'
  | 'dan-mach'
  | 'thuy-si'
  | 'ukraina'
  | 'han-quoc'
  | 'au-my'
  | 'an-do'
  | 'canada'
  | 'tay-ban-nha'
  | 'indonesia'
  | 'ba-lan'
  | 'malaysia'
  | 'bo-dao-nha'
  | 'uae'
  | 'chau-phi'
  | 'a-rap-xe-ut'
  | 'nhat-ban'
  | 'dai-loan'
  | 'anh'
  | 'quoc-gia-khac'
  | 'tho-nhi-ky'
  | 'nga'
  | 'uc'
  | 'brazil'
  | 'y'
  | 'na-uy'
  | 'nam-phi';

export type MovieType =
  | 'phim-le'
  | 'phim-bo'
  | 'phim-chieu-rap'
  | 'hoat-hinh'
  | 'tv-shows'
  | 'phim-vietsub'
  | 'phim-thuyet-minh'
  | 'phim-long-tieng'
  | 'subteam'
  | 'latest';

export type Language = 'long-tieng' | 'thuyet-minh' | 'vietsub';
export interface IBaseItem {
  id: string;
  name: string;
  slug: Country | Category;
}
